# Generated by Django 6.0.1 on 2026-01-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('deals', '0002_deal_company_deal_contact'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='contacts.contact', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='task',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='deals.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('call', 'Звонок'), ('meeting', 'Встреча'), ('email', 'Письмо'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
