# Generated by Django 6.0.1 on 2026-01-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сделки')),
                ('stage', models.CharField(choices=[('lead', 'Лид'), ('contact', 'Контакт'), ('proposal', 'Предложение'), ('negotiation', 'Переговоры'), ('contract', 'Договор'), ('won', 'Успех'), ('lost', 'Потеря')], default='lead', max_length=20, verbose_name='Стадия')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('probability', models.IntegerField(default=0, verbose_name='Вероятность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='users.customuser', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
    ]
